Repository zulip/zulip-flutter, pull requests merged in 2024-09, with the labels that each got.

#911 i18n: Consistently use … in favor of ...
  assets/l10n/app_en.arb
  test/widgets/compose_box_test.dart
Labels: a-i18n, integration review

#927 msglist: Fix mark-as-read button icon color in dark mode
  lib/widgets/message_list.dart
Labels: a-msglist, integration review

#931 channel [nfc]: Document methods on ChannelStore; expose debugTopicVisibility directly
  lib/model/channel.dart
  lib/model/store.dart
  test/model/channel_test.dart
Labels: maintainer review

#932 test: Use random topic in eg.streamMessage
  test/example_data.dart
Labels: maintainer review

#936 store [nfc]: Remove completed TODO
  lib/model/store.dart
Labels: integration review

#919 Handle the case when a code block has no grandchildren
  lib/model/content.dart
  test/model/content_test.dart
Labels: integration review

#900 msglist: Implement new edited/moved label design.
  assets/icons/ZulipIcons.ttf
  assets/icons/edited.svg
  assets/icons/message_moved.svg
  assets/l10n/app_en.arb
  lib/widgets/edit_state_marker.dart
  lib/widgets/icons.dart
  lib/widgets/message_list.dart
  lib/widgets/theme.dart
  test/widgets/message_list_test.dart
Labels: integration review

#909 Handle disposal of message store correctly.
  lib/model/message.dart
  lib/model/store.dart
  test/model/message_test.dart
  test/model/store_test.dart
Labels: integration review

#940 test: Use random email in eg.user
  test/example_data.dart
Labels: integration review

#947 check: Use --text when potentially diffing generated files
  tools/check
Labels: a-tools, integration review

#956 macos: Take in automatic override of `applicationSupportsSecureRestorableState`
  macos/Runner/AppDelegate.swift
Labels: maintainer review, integration review

#951 deps: Upgrade video_player_android to 2.7.3
  pubspec.lock
Labels: integration review

#958 ios: Add workaround for package:firebase_messaging when building with Xcode 16
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Flutter/Zulip.xcconfig
  ios/Runner.xcodeproj/project.pbxproj
Labels: maintainer review, integration review

#937 lightbox: Replace onDismiss with `await showErrorDialog`
  lib/widgets/dialog.dart
  lib/widgets/lightbox.dart
Labels: integration review

#968 deps: Upgrade Flutter SDK and `video_player_android`
  pubspec.lock
  pubspec.yaml
Labels: maintainer review
