Repository zulip/zulip-flutter, pull requests merged in 2024-07, with the labels that each got.

#777 deps: Upgrade `flutter_local_notifications` and `Flutter` to the latest
  pubspec.lock
  pubspec.yaml
Labels: integration review

#713 msglist: Add "Copy message link" button to action sheet
  assets/l10n/app_en.arb
  lib/widgets/action_sheet.dart
  test/widgets/action_sheet_test.dart
Labels: integration review

#789 code_block: Fix null-check `!` errors during hot reloads
  lib/widgets/code_block.dart
  test/widgets/code_block_test.dart
Labels: a-content

#778 Intl: Rename stream to channel in translation labels
  assets/l10n/app_en.arb
  assets/l10n/app_ja.arb
  docs/translation.md
  lib/widgets/app.dart
  lib/widgets/compose_box.dart
Labels: maintainer review, integration review

#793 login: Show `visiblePassword` type keyboard only when password is unobscured
  lib/widgets/login.dart
Labels: integration review

#804 theme: Implement DesignVariables.dark
  lib/widgets/theme.dart
  test/widgets/theme_test.dart
Labels: integration review

#819 compose box: On failed message send, show error dialog
  lib/widgets/compose_box.dart
  test/widgets/compose_box_test.dart
Labels: a-compose, integration review

#835 lightbox test: Add basic tests for image lightbox
  test/widgets/lightbox_test.dart
Labels: maintainer review

#802 docs: Create setup guide, Add guide to setup on a cloud server
  README.md
  docs/setup.md
Labels: buddy review

#840 api/notif: Rename FcmMessageStreamRecipient to FcmMessageChannelRecipient
  lib/api/notifications.dart
  lib/api/notifications.g.dart
  lib/notifications/display.dart
  test/api/notifications_test.dart
Labels: integration review

#841 api: Rename stream to channel in events
  lib/api/model/events.dart
  lib/api/model/events.g.dart
  lib/model/channel.dart
  lib/model/store.dart
  test/model/test_store.dart
  test/widgets/message_list_test.dart
Labels: integration review

#839 api: Rename `UnreadStreamSnapshot` to `UnreadChannelSnapshot`
  lib/api/model/initial_snapshot.dart
  lib/api/model/initial_snapshot.g.dart
  lib/model/unreads.dart
  test/api/model/initial_snapshot_test.dart
  test/example_data.dart
  test/model/unreads_test.dart
  test/widgets/message_list_test.dart
  test/widgets/subscription_list_test.dart
Labels: integration review
