Repository zulip/zulip-flutter, pull requests merged in 2024-10, with the labels that each got.

#954 msglist: Follow web's change making dark mode's --color-text-default opaque
  lib/widgets/content.dart
  lib/widgets/message_list.dart
Labels: integration review

#972 api: Use streaming UTF-8 + JSON decoding for the response
  lib/api/core.dart
Labels: integration review

#983 deps: Upgrade video_player_android to 2.7.8
  pubspec.lock
Labels: integration review

#975 backoff: Make duration bounds customizable
  lib/api/backoff.dart
  test/api/backoff_test.dart
Labels: a-api, maintainer review

#990 compose_box [nfc]: Add InsetShadowBox
  lib/widgets/inset_shadow.dart
  test/flutter_checks.dart
  test/widgets/inset_shadow_test.dart
Labels: integration review

#994 deps: Make flutter_checks and legacy_checks direct dev dependencies
  pubspec.lock
  pubspec.yaml
Labels: maintainer review

#993 actions test: Await all responses; cut pumpAndSettle
  test/widgets/actions_test.dart
Labels: maintainer review

#986 icons: Updated bot icon with single antenna version.
  assets/icons/ZulipIcons.ttf
  assets/icons/bot.svg
Labels: integration review

#1005 store [nfc]: Offer singleton global store on binding
  lib/model/binding.dart
  lib/widgets/store.dart
  test/model/binding.dart
Labels: maintainer review

#1018 deps: Upgrade Flutter to 3.27.0-1.0.pre.166
  pubspec.lock
  pubspec.yaml
Labels: integration review

#1022 home: Remove irrelevant information from early prototyping
  assets/l10n/app_en.arb
  lib/widgets/app.dart
Labels: integration review

#1021 content: Handle code block spans with multiple CSS classes
  lib/model/content.dart
  test/model/content_test.dart
  test/widgets/content_test.dart
Labels: integration review

#1027 test: Fix flake with identical consecutively autogenerated email addresses
  test/example_data.dart
Labels: integration review

#1030 test: Bump eg.recentZulipFeatureLevel and recentZulipVersion to 9.0
  test/example_data.dart
Labels: maintainer review
