Repository zulip/zulip-flutter, pull requests merged in 2024-06, with the labels that each got.

#704 internal_link: Recognize channel operator in narrow links
  lib/model/internal_link.dart
  lib/model/internal_link.g.dart
  test/model/internal_link_test.dart
Labels: mentor review, maintainer review, integration review

#729 internal_link: Parse topic permalinks
  lib/model/internal_link.dart
  lib/model/internal_link.g.dart
  test/model/internal_link_test.dart
Labels: maintainer review

#738 content/msglist: Fix vertical position of horizontal scrollbar in codeblock
  lib/widgets/message_list.dart
  test/widgets/message_list_test.dart
Labels: a-content, a-msglist

#748 compose_box [nfc]: Update some stale issue references
  lib/widgets/compose_box.dart
Labels: integration review

#760 code_block [nfc]: Update outdated comment
  lib/widgets/code_block.dart
Labels: integration review
