Repository zulip/zulip-flutter, pull requests merged in 2025-07, with the labels that each got.

#1638 msglist: Show recipient headers on all messages, in Mentions / Starred
  lib/model/message_list.dart
  test/model/message_list_test.dart
Labels: integration review

#1657 msglist: Tapping a message in Starred or Mentions opens anchored msglist
  lib/widgets/message_list.dart
  test/widgets/message_list_checks.dart
  test/widgets/message_list_test.dart
Labels: integration review

#1601 KaTeX (4/n): Ignore classes that don't have CSS definition
  lib/model/katex.dart
Labels: integration review

#1658 api: Remove backward-compat code for mark-read protocol in FL <155
  lib/api/route/messages.dart
  lib/model/unreads.dart
  lib/widgets/actions.dart
  test/api/route/messages_test.dart
  test/widgets/actions_test.dart
Labels: a-api, integration review

#1628 Decrease whitespace at end of message feed
  lib/widgets/message_list.dart
Labels: integration review, launch feedback

#1625 msglist: Use icon for topic-list button in app bar
  assets/l10n/app_de.arb
  assets/l10n/app_en.arb
  assets/l10n/app_it.arb
  assets/l10n/app_pl.arb
  assets/l10n/app_ru.arb
  assets/l10n/app_sl.arb
  assets/l10n/app_uk.arb
  assets/l10n/app_zh_Hans_CN.arb
  assets/l10n/app_zh_Hant_TW.arb
  lib/generated/l10n/zulip_localizations.dart
  lib/generated/l10n/zulip_localizations_ar.dart
  lib/generated/l10n/zulip_localizations_de.dart
  lib/generated/l10n/zulip_localizations_en.dart
  lib/generated/l10n/zulip_localizations_it.dart
  lib/generated/l10n/zulip_localizations_ja.dart
  lib/generated/l10n/zulip_localizations_nb.dart
  lib/generated/l10n/zulip_localizations_pl.dart
  lib/generated/l10n/zulip_localizations_ru.dart
  lib/generated/l10n/zulip_localizations_sk.dart
  lib/generated/l10n/zulip_localizations_sl.dart
  lib/generated/l10n/zulip_localizations_uk.dart
  lib/generated/l10n/zulip_localizations_zh.dart
  lib/widgets/message_list.dart
  test/widgets/message_list_test.dart
  test/widgets/topic_list_test.dart
Labels: integration review

#1550 home [nfc]: Clean up some dead safe-area code from before bottom-tabs
  lib/widgets/inbox.dart
  lib/widgets/recent_dm_conversations.dart
  lib/widgets/subscription_list.dart
Labels: integration review

#1690 ci: Work around accidental desync of Flutter main branch
  .github/workflows/ci.yml
Labels: upstream

#1720 Render KaTeX by default
  lib/model/settings.dart
  test/model/content_test.dart
  test/widgets/content_test.dart
Labels: maintainer review

#1719 presence: Dispose Presence object when store disposed
  lib/model/store.dart
Labels: maintainer review

#1731 readme: Remove a "this beta app" reference
  README.md
Labels: integration review

#1738 deps: Upgrade Flutter to 3.33.0-1.0.pre-1086
  pubspec.lock
  pubspec.yaml
Labels: integration review

#1742 katex: Remove renderKaTex experimental flag
  lib/model/katex.dart
  lib/model/settings.dart
  test/model/content_test.dart
  test/model/katex_test.dart
  test/widgets/content_test.dart
  test/widgets/katex_test.dart
  tools/content/unimplemented_katex_test.dart
Labels: integration review

#1760 readme: Link to Greg's "secret" to using `git log -p`
  README.md
Labels: integration review
