Repository zulip/zulip-flutter, pull requests merged in 2025-06, with the labels that each got.

#1542 licenses: Add asset entry for KaTeX license
  pubspec.yaml
  test/licenses_test.dart
Labels: integration review

#1562 settings [nfc]: Suppress some new deprecation warnings
  lib/widgets/settings.dart
  test/flutter_checks.dart
Labels: integration review

#1552 home: Add placeholder text for empty Inbox, Channels, and Direct messages
  assets/l10n/app_en.arb
  lib/generated/l10n/zulip_localizations.dart
  lib/generated/l10n/zulip_localizations_ar.dart
  lib/generated/l10n/zulip_localizations_de.dart
  lib/generated/l10n/zulip_localizations_en.dart
  lib/generated/l10n/zulip_localizations_ja.dart
  lib/generated/l10n/zulip_localizations_nb.dart
  lib/generated/l10n/zulip_localizations_pl.dart
  lib/generated/l10n/zulip_localizations_ru.dart
  lib/generated/l10n/zulip_localizations_sk.dart
  lib/generated/l10n/zulip_localizations_uk.dart
  lib/generated/l10n/zulip_localizations_zh.dart
  lib/widgets/home.dart
  lib/widgets/inbox.dart
  lib/widgets/recent_dm_conversations.dart
  lib/widgets/subscription_list.dart
  lib/widgets/theme.dart
  test/widgets/inbox_test.dart
  test/widgets/recent_dm_conversations_test.dart
  test/widgets/subscription_list_test.dart
Labels: integration review

#1538 local echo (6.75/7): Revised commit for local echo (sans retrieving failed outbox content)
  lib/model/message.dart
  lib/model/message_list.dart
  lib/widgets/message_list.dart
  test/api/model/model_checks.dart
  test/model/message_list_test.dart
  test/model/message_test.dart
  test/widgets/message_list_test.dart
Labels: integration review

#1453 local echo (7/7): Support simplified version of local echo
  assets/l10n/app_en.arb
  assets/l10n/app_pl.arb
  assets/l10n/app_ru.arb
  lib/generated/l10n/zulip_localizations.dart
  lib/generated/l10n/zulip_localizations_ar.dart
  lib/generated/l10n/zulip_localizations_de.dart
  lib/generated/l10n/zulip_localizations_en.dart
  lib/generated/l10n/zulip_localizations_ja.dart
  lib/generated/l10n/zulip_localizations_nb.dart
  lib/generated/l10n/zulip_localizations_pl.dart
  lib/generated/l10n/zulip_localizations_ru.dart
  lib/generated/l10n/zulip_localizations_sk.dart
  lib/generated/l10n/zulip_localizations_uk.dart
  lib/generated/l10n/zulip_localizations_zh.dart
  lib/model/message.dart
  lib/widgets/compose_box.dart
  lib/widgets/message_list.dart
  test/widgets/compose_box_test.dart
  test/widgets/message_list_test.dart
Labels: maintainer review, integration review

#1575 msglist: Say "Quote message" for the quote-and-reply button, following web
  assets/l10n/app_en.arb
  lib/generated/l10n/zulip_localizations.dart
  lib/generated/l10n/zulip_localizations_ar.dart
  lib/generated/l10n/zulip_localizations_de.dart
  lib/generated/l10n/zulip_localizations_en.dart
  lib/generated/l10n/zulip_localizations_it.dart
  lib/generated/l10n/zulip_localizations_ja.dart
  lib/generated/l10n/zulip_localizations_nb.dart
  lib/generated/l10n/zulip_localizations_pl.dart
  lib/generated/l10n/zulip_localizations_ru.dart
  lib/generated/l10n/zulip_localizations_sk.dart
  lib/generated/l10n/zulip_localizations_sl.dart
  lib/generated/l10n/zulip_localizations_uk.dart
  lib/generated/l10n/zulip_localizations_zh.dart
  lib/widgets/action_sheet.dart
Labels: integration review

#1595 More error tolerance in migrating legacy data
  lib/model/legacy_app_data.dart
Labels: maintainer review

#1597 settings: Reword to "in conversation views" consistently
  assets/l10n/app_en.arb
  lib/generated/l10n/zulip_localizations.dart
  lib/generated/l10n/zulip_localizations_ar.dart
  lib/generated/l10n/zulip_localizations_en.dart
  lib/generated/l10n/zulip_localizations_ja.dart
  lib/generated/l10n/zulip_localizations_nb.dart
  lib/generated/l10n/zulip_localizations_sk.dart
  lib/generated/l10n/zulip_localizations_uk.dart
  lib/generated/l10n/zulip_localizations_zh.dart
Labels: maintainer review
