Repository zulip/zulip-flutter, pull requests merged in 2025-02, with the labels that each got.

#1233 compose: Make compose-box border more prominent in dark mode
  lib/widgets/compose_box.dart
  lib/widgets/theme.dart
  test/widgets/compose_box_test.dart
Labels: maintainer review, integration review

#1324 android build: Allow gradle to use more memory
  android/gradle.properties
Labels: integration review

#1331 Attempt to fix JVM high memory usage in CI
  android/gradle.properties
Labels: integration review

#1323 msglist: Update label to 'Messages with yourself' in DM header
  assets/l10n/app_en.arb
  lib/generated/l10n/zulip_localizations.dart
  lib/generated/l10n/zulip_localizations_ar.dart
  lib/generated/l10n/zulip_localizations_en.dart
  lib/generated/l10n/zulip_localizations_ja.dart
  lib/generated/l10n/zulip_localizations_nb.dart
  lib/generated/l10n/zulip_localizations_sk.dart
  lib/widgets/message_list.dart
Labels: integration review

#1156 content: Handle multiple math blocks in `<p>`
  lib/model/content.dart
  test/model/content_test.dart
Labels: integration review

#1249 msglist: Move star icon 2px away from the edge of the screen
  lib/widgets/message_list.dart
Labels: integration review

#1326 home: Center align the "try another account" message in loading placeholder
  lib/widgets/home.dart
Labels: integration review

#1367 compose [nfc]: Simplify content-input state, deduplicating topic text
  lib/widgets/compose_box.dart
Labels: maintainer review

#1376 mailmap: Update Rajesh's entry
  .mailmap
Labels: integration review

#1380 check: Ensure GNU coreutils are used on macOS
  tools/check
Labels: integration review
